#!/usr/bin/env bash
# Configures a new Ubuntu machine to add X-Served-By header in Nginx response
apt-get update -y
apt-get install -y nginx

SERVER_HOSTNAME=$(hostname)

printf "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\n\tserver_name _;\n\n\tadd_header X-Served-By %s always;\n\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}\n" "$SERVER_HOSTNAME" > /etc/nginx/sites-available/default

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx
