#!/usr/bin/env bash
# Configures Nginx with custom HTTP response header X-Served-By
apt-get update -y
apt-get install nginx -y
mkdir -p /var/www/html
echo "Holberton School for the win!" | tee /var/www/html/index.html > /dev/null
printf "Ceci n'est pas une page\n" | tee /var/www/html/404.html > /dev/null
HOSTNAME=$(hostname)
sed -i 's#server_name _;#server_name _;\n\tadd_header X-Served-By '"$HOSTNAME"';#' /etc/nginx/sites-available/default
service nginx restart