#!/usr/bin/env bash
# Configures a new Ubuntu machine to add X-Served-By header in Nginx response
apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

cat > /etc/nginx/sites-available/default << NGINXEOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By "$HOSTNAME" always;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
NGINXEOF

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx
