#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# The redirection is a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Write nginx default config with 301 redirect for /redirect_me
cat << 'EOF' | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.wilsonn.vercel.app;
	}
	location / {
		try_files $uri $uri/ =404;
	}
}
EOF

sudo service nginx restart