#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# The redirection is a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Replace server_name _; with the redirect block (replace a line with multiple lines using sed)
sudo sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.wilsonn.vercel.app;\n\t}|' /etc/nginx/sites-available/default

sudo service nginx restart