#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Write nginx default config with custom 404 error page and redirect
cat << 'EOF' | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	error_page 404 /404.html;
	location /redirect_me {
		return 301 https://www.wilsonn.vercel.app;
	}
	location / {
		try_files $uri $uri/ =404;
	}
}
EOF

sudo service nginx restart